name: Run python unit tests

on: [push, pull_request_target]

jobs:
  run-tests:
    environment: unit test environment
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file
        env:
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: |
          echo "BOT_NAME=nhl_gdt_bot" >> .env
          echo "PASSWORD=$BOT_PASSWORD" >> .env
          echo "LEMMY_INSTANCE=lemmy.world" >> .env
          echo "COMMUNITY_NAME=test5677754@lemmy.world" >> .env
          echo "GDT_POST_TYPES=POSTSEASON,ALLSTAR,PRESEASON,REGULAR" >> .env
      - name: Run unit tests
        run: |
          pytest
