name: Run python unit tests

on: [push, pull_request]

jobs:
  run-tests:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        env:
          BOT_NAME: nhl_gdt_bot
          PASSWORD: ${{ secrets.TEST_SECRET }}
          LEMMY_INSTANCE: lemmy.world
          COMMUNITY_NAME: test5677754@lemmy.world
          GDT_POST_TYPES: POSTSEASON,ALLSTAR,PRESEASON,REGULAR
        run: |
          pytest
