name: Run python unit tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-tests:
    environment: unit test environment
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"
          exit 1
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # This is dangerous without the first access check
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file
        env:
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: |
          echo "BOT_NAME=nhl_gdt_bot" >> .env
          echo "PASSWORD=$BOT_PASSWORD" >> .env
          echo "LEMMY_INSTANCE=lemmy.world" >> .env
          echo "COMMUNITY_NAME=test5677754@lemmy.world" >> .env
          echo "GDT_POST_TYPES=POSTSEASON,ALLSTAR,PRESEASON,REGULAR" >> .env
      - name: Run unit tests
        run: |
          pytest
